### ISSUE TITLE
Do you have any opinions on Vue.js

### ISSUE THREAD

**Issue by dan-gamble** [MoOx/ama#14]
http://vuejs.org/

As someone who is heavily invested in React do you look at other frontend frameworks much?

**Comment by MoOx** [comment]
Sorry in advance if my response is too simple.

_I didn't tried this yet and don't plan too._

**Having html and js is imo too error prone.**

This looks like a mix of backbone (view) + angular (custom magic attributes) and I think those things should be behind us.

I definitely prefer something more reliable like React + JSX + Flow. And tests are more easy with this combo as you don't need the DOM.
