### ISSUE TITLE
What's your opinion on the current state of CSS

### ISSUE THREAD

**Issue by dan-gamble** [MoOx/ama#15]
The whole landscape per-se, including the likes of pre-processors, PostCSS, etc. Do you feel the CSS environment is in a healthy place / getting there / heading down the wrong path?

**Comment by MoOx** [comment]
I do think CSS is not appropriate for modern apps.
It seems like a legacy language that make sense with a document approach, but we are not serving document anymore.

See https://speakerdeck.com/vjeux/react-css-in-js?slide=2

Currently I am writing inline styles when I don't have pre-rendering involved and CSS with CSS Modules (when I do have pre-rendering) but I plan to try to implement a nice UX to serve prerendered (for SEO) content that can be adjusted client side (inline styles don't have MQ, so everything depends on the runtime).

To be honest, I don't see myself using "normal" CSS in a near future. Only a subset like the one we can currently find in react-native or react-native-web (see https://github.com/facebook/css-layout).
