### ISSUE TITLE
What do you think of inline style in React?

### ISSUE THREAD

**Issue by amsdamsgram** [MoOx/ama#17]
Hi,

what do you think of inline style in React?
I'm starting to see few people talking about [aphrodite](https://github.com/Khan/aphrodite)
Have you ever tried it?

I am currently using PostCSS + Css-modules and I think it's great but aphrodite seems a good tool to do exactly the same but inline.

**Comment by MoOx** [comment]
See https://github.com/MoOx/ama/issues/15. Tell me if this answer your question (if so, please close this issue ^^).

**Comment by iDams** [comment]
It does ;)
