### ISSUE TITLE
DuckDuckGo

### ISSUE THREAD

**Issue by amsdamsgram** [MoOx/ama#18]
Hi MoOx,

I remember you use [DuckDuckGo](https://duckduckgo.com).
Are search results relevant?
Do you ever use google search engine sometimes?

**Comment by MoOx** [comment]
Already answered here https://github.com/MoOx/ama/issues/16.
FYI, I am trying http://qwant.com/ since this morning :)

**Comment by amsdamsgram** [comment]
Arf, my bad. I forgot to look in closed issues.
I will be interesting in your feelings about qwant too!
Thanks!
