### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [MoOx/ama#2]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by MoOx** [comment]
My current editor is Atom. I tried in the past the following: Notepad++, SciTE, Eclipse, NetBeans, WebStorm, Textmate, Sublime Text 2, Vim.

My terminal is Terminal.app but I plan to use [black-screen](https://github.com/shockone/black-screen) soon. I used iTerm in the past but don't really needs what it brings. I use zsh and [pure](https://github.com/sindresorhus/pure) prompt.

My monospaced font is Menlo but I also used Monaco for a while.

I use Firefox Nightly as my main browser for ethical reasons. I don't really like Google practices (make money with ads based on personal data) so Chrome is not a choice for me. Safari wasn't enough for me last time I tried it for a while.

My entire machine setup is versionned in my [setup](https://github.com/MoOx/setup) which is a sort of dotfiles repo but on steroid. I plan to extract a core as [setupsh](http://github.com/MoOx/setupsh) but never finished the job :)
Everything I use is listed in the [setup/index](https://github.com/MoOx/setup/blob/master/index) so take a look here :)

When I start to work on a project most of the time, I open a terminal, cd to the project, run:

``` console
$ git pull

# open GitHub Desktop.app
$ gh

# Atom.app
$ atom .

# start build/watcher/server...
$ npms
# npms is an alias that does npm i + npm start to get missing package if needed (see the git pull above)
```

I like to have a simple process so if it's more complicated I will work on it to simplify it.

After those simple line I should be ready to work with fullscreen apps (most of the time).

I work at home in a dedicated room (my office) on a iMac 27" on a [convertible standing desk](http://www.ikea.com/us/en/catalog/products/S29022488/) with a [Fluidstance level](http://www.fluidstance.com/product/the-original).
I will try to post a photo of my office soon but it's currently a WIP.
I also have a Macbook Air 13" when I visit a client (reminder: I am freelance and do consulting & custom developments)

My machines are synced with my setup mentionned above + currently "Bittorent Sync" for data/repos etc but I am currently considering using [Syncthing](http://syncthing.net/).

Do not hesitate to ask more details, I probably missed a lot of things ^^.

**Comment by sindresorhus** [comment]
:+1:
