### ISSUE TITLE
Do you think websites that make money can respect W3C?

### ISSUE THREAD

**Issue by darenju** [MoOx/ama#5]
Heard today at my job: "Fuck standards, we need the site to work."
Added later: "Websites that make money cannot respect W3C standards."

Kinda disagree with this... What's your opinion?

**Comment by MoOx** [comment]
Money or not, it's hard to validate everything. Just try to validate google homepage (lol).
I think it's very nice to follow standards in general, but sometimes, you prefer to not waste time on "not useful" stuff (for user experience). At the end it's just a matter of time. And "time is money". Well, the loop is complete.
