### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by tenhobi** [MoOx/ama#9]

**Comment by MoOx** [comment]
No. And I don't want to. I am not even sure I will try a "web component" approach soon.
If I have to I will probably take a look to Bosonic, (which follow the specs).

I am more a React fan and don't really see myself going backward to handle lots of dom sync problem.

This comment is pretty much what my feeling about web component atm: https://github.com/facebook/react/issues/5052#issuecomment-145594782
